"""db_init

Revision ID: 020cab88ab14
Revises: 
Create Date: 2025-06-02 09:04:05.861670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '020cab88ab14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('expression', sa.String(length=256), nullable=False),
    sa.Column('result', sa.Float(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'expression', name='uix_user_expression')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operations')
    # ### end Alembic commands ###
